---
- name: Task
  hosts: servers
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Print the hostname
      debug:
        msg: "host: {{ inventory_hostname }}"

    - name: Remove old Docker versions
      become: yes
      apt:
        name: 
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
        force: yes

    - name: Update apt packages
      become: yes
      apt:
        update_cache: yes

    - name: Install dependencies
      become: yes
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Create directory for apt keyrings
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      become: yes
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
        state: present
        filename: docker

    - name: Update apt packages again
      become: yes
      apt:
        update_cache: yes

    - name: Install Docker packages
      become: yes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Create Docker group
      become: yes
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Refresh group membership
      command: newgrp docker
      become_user: "{{ ansible_user_id }}"

    - name: Run Docker hello-world
      command: docker run hello-world
      register: docker_output

    - name: Debug Docker hello-world output
      debug:
        var: docker_output.stdout