---
- name: Task
  hosts: k8s
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Print the hostname
      debug:
        msg: "host: {{ inventory_hostname }}"

    - name: Install Kubernetes Python library for Ansible
      pip:
        name: kubernetes==30.1.0
        extra_args: --break-system-packages

    - name: Ensure Kubernetes namespaces exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ item }}'
        state: present
      loop:
        - kubearmor

    - name: Add KubeArmor Helm repository
      kubernetes.core.helm_repository:
        name: kubearmor
        url:  https://kubearmor.github.io/charts

    - name: helm repo update
      register: repoupdate
      command: helm repo update 
    - debug: msg="{{ repoupdate.stdout }}"

    - name: Install KubeArmor chart
      register: kubearmor_install
      kubernetes.core.helm:
        chart_ref: kubearmor/kubearmor-operator
        name: kubearmor-operator
        namespace: kubearmor
    - debug: msg="{{ kubearmor_install.stdout }}"